version: '3.1'
services:
  plex:
    image: lscr.io/linuxserver/plex:1.41.3.9314-a0bfb8370-ls249
    container_name: plex
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
    ports:
      - 32400:32400
    volumes:
      - ./config:/config
      - ./tvseries:/tv
      - ./movies:/movies
    restart: unless-stopped