services:
  thelounge:
    image: ghcr.io/thelounge/thelounge:latest
    container_name: thelounge
    restart: unless-stopped
    ports:
      - 9001:9000
    volumes:
      - ./thelounge:/var/opt/thelounge