services:
  comfyui:
    env_file: .env
    container_name: comfyui
    image: ${COMFYUI_IMAGE:-yanwk/comfyui-boot:cu121}
    restart: unless-stopped
    volumes:
      - ${COMFYUI_STORAGE:-./comfy_storage}:/root
    environment:
      CLI_ARGS: ""
    ports:
      - "8188:8188"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ["0"]
            capabilities: [gpu]

  ollama:
    env_file: .env
    container_name: ollama
    image: ${OLLAMA_IMAGE:-ollama/ollama:latest}
    restart: unless-stopped
    volumes:
      - ${OLLAMA_STORAGE:-./ollama-webui}:/root/.ollama
    pull_policy: ${OPEN_WEBUI_PULL:-missing}
    tty: ${OLLAMA_TTY:-true}
    ports:
     - ${OLLAMA_PORT:-11434}:11434
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ["0"]
            capabilities: [gpu]

  open-webui:
    env_file: .env
    container_name: open-webui
    image: ${OPEN_WEBUI_IMAGE:-ghcr.io/open-webui/open-webui:main}
    volumes:
      - ${OPEN_WEBUI_STORAGE:-./open-webui}:/app/backend/data
    pull_policy: ${OPEN_WEBUI_PULL:-missing}
    depends_on:
      - ollama
    ports:
      - ${OPEN_WEBUI_PORT:-3000}:8080
    environment:
      - 'WEBUI_SECRET_KEY='
      - OLLAMA_ORIGINS="*"
      - OLLAMA_HOST="0.0.0.0:${OLLAMA_PORT}"
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

  ollama:
    env_file: .env
    container_name: ollama
    restart: unless-stopped
    volumes:
      - ${OLLAMA_STORAGE:-./ollama-webui}:/root/.ollama
    pull_policy: ${OLLAMA_PULL:-missing}
    tty: true
    ports:
     - ${OLLAMA_PORT:-11434}:11434
    image: ${OLLAMA_IMAGE:-ollama/ollama:${OLLAMA_DOCKER_TAG:-latest}}
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ["0"]
            capabilities: [gpu]