services:
  ollama:
    env_file:
      - path: ollama.env
        required: true
    container_name: ${OLLAMA_CONTAINER_NAME:-ollama}
    image: ${OLLAMA_IMAGE:-ollama/ollama:latest}
    volumes:
      - ${OLLAMA_STORAGE:-./ollama-webui}:/root/.ollama
    restart: ${OLLAMA_RESTART_POLICY:-unless-stopped}
    tty: ${OLLAMA_TTY:-true}
    ports:
     - ${OLLAMA_PORT:-11434}:11434
    networks:
      - net
    deploy:
      resources:
        limits:
          memory: ${OLLAMA_MEMORY_LIMIT:-2g}
        reservations:
          memory: ${OLLAMA_MEMORY_RESERVATION:-1g}
          devices:
          - driver: ${GPU_DRIVER:-nvidia}
            device_ids: ["0"]
            capabilities: [gpu]
  comfyui:
    env_file:
      - path: comfy.env
        required: true
    container_name: ${COMFYUI_CONTAINER_NAME:-comfyui}
    image: ${COMFYUI_IMAGE:-yanwk/comfyui-boot:cu121}
    volumes:
      - ${COMFYUI_STORAGE_MODELS:-./comfy-storage/models}:/home/runner/ComfyUI/models
      - ${COMFYUI_STORAGE_OUTPUT:-./comfy-storage/output}:/home/runner/ComfyUI/output
    restart: ${COMFYUI_RESTART_POLICY:-unless-stopped}
    tty: ${COMFYUI_TTY:-true}
    ports:
     - ${COMFYUI_PORT:-8188}:8188
    networks:
      - net
    deploy:
      resources:
        reservations:
          devices:
          - driver: ${GPU_DRIVER:-nvidia}
            device_ids: ["0"]
            capabilities: [gpu]
  open-webui:
    env_file:
      - path: ui.env
        required: true
    container_name: ${OPEN_WEBUI_CONTAINER_NAME:-open-webui}
    image: ${OPEN_WEBUI_IMAGE:-ghcr.io/open-webui/open-webui:main}
    volumes:
      - ${OPEN_WEBUI_STORAGE:-./open-webui}:/app/backend/data
    restart: ${OPEN_WEBUI_RESTART_POLICY:-unless-stopped}
    tty: ${OPEN_WEBUI_TTY:-true}
    ports:
     - ${OPEN_WEBUI_PORT:-3000}:8080
    networks:
      - net
    deploy:
      resources:
        reservations:
          devices:
          - driver: ${GPU_DRIVER:-nvidia}
            device_ids: ["0"]
            capabilities: [gpu]
  qdrant:
    env_file:
      - path: qdrant.env
        required: true
    container_name: ${QDRANT_CONTAINER_NAME:-qdrant}
    image: ${QDRANT_IMAGE:-qdrant/qdrant:latest}
    restart: ${QDRANT_RESTART_POLICY:-unless-stopped}
    tty: ${QDRANT_TTY:-true}
    ports:
     - ${QDRANT_PORT:-6333}:6333
    volumes:
     - ${QDRANT_STORAGE:-./qdrant-storage}:/qdrant/storage:z
    networks:
      - net

networks:
  net:
    driver: bridge